import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useLobbyStore } from '../store/lobbyStore';

/**
 * CreateTeam: UI for creating a new lobby/room
 * 
 * BACKEND INTEGRATION POINTS:
 * 
 * Current Flow (Mock):
 *   1. User enters room name + max players
 *   2. Click "Create Team" → calls store.createLobby()
 *   3. Store creates local lobby object
 *   4. Navigate to LobbyScreen
 * 
 * Future Flow (With Backend):
 *   1. User enters room name + max players
 *   2. Click "Create Team" → POST /api/lobbies
 *      Payload: {
 *        roomName: string,
 *        maxPlayers: number,
 *        createdBy: currentUserId
 *      }
 *   3. Server responds:
 *      {
 *        roomId: string,         // UUID generated by server
 *        roomCode: string,       // 6-char code (e.g., "ABC123") for sharing
 *        phase: "LOBBY",         // LOBBY_PHASES.LOBBY
 *        players: [              // List of players
 *          { id, name, ready: false, score: 0, ... }
 *        ],
 *        createdAt: timestamp,
 *        ...
 *      }
 *   4. Store saves response
 *   5. WebSocket connects and subscribes to room updates
 *   6. Navigate to LobbyScreen
 * 
 * Error Handling (TODO: BACKEND):
 *   - Room name already exists → show error
 *   - Max players invalid (< 2 or > 8) → show error
 *   - Server error (DB failure, etc) → show error with retry
 *   - Network timeout → show error with retry
 * 
 * Validation (Current):
 *   ✅ Room name not empty
 *   ✅ User has currentUserId and currentUserName
 *   ⚠️ Max players in range [2, 4] (hardcoded)
 * 
 * Validation (TODO: BACKEND):
 *   - Room name length (min 3, max 50 chars)
 *   - Room name no special chars (alphanumeric + spaces)
 *   - Room name not offensive (content filter)
 *   - Max players in range [2, 8]
 *   - User not already in another active lobby
 */

const CreateTeam = () => {
  const [roomName, setRoomName] = useState('');
  const [maxPlayers, setMaxPlayers] = useState(4);
  const [isLoading, setIsLoading] = useState(false);  // TODO: BACKEND - show during POST request
  const [error, setError] = useState(null);           // TODO: BACKEND - display error messages
  const navigate = useNavigate();
  const currentUserId = useLobbyStore((state) => state.currentUserId);
  const currentUserName = useLobbyStore((state) => state.currentUserName);
  const createLobby = useLobbyStore((state) => state.createLobby);

  const handleCreate = async () => {
    // CLIENT-SIDE VALIDATION
    if (!roomName.trim()) {
      alert('Please enter a room name');
      return;
    }
    if (!currentUserId || !currentUserName) {
      alert('Please set a username first!');
      return;
    }

    setIsLoading(true);
    setError(null);

    try {
      // TODO: BACKEND - Replace with real API call
      // const response = await fetch('/api/lobbies', {
      //   method: 'POST',
      //   headers: { 'Content-Type': 'application/json' },
      //   body: JSON.stringify({
      //     roomName: roomName.trim(),
      //     maxPlayers,
      //     createdBy: currentUserId
      //   })
      // });
      //
      // if (!response.ok) {
      //   const errorData = await response.json();
      //   throw new Error(errorData.message || 'Failed to create room');
      // }
      //
      // const lobbyData = await response.json();
      // useLobbyStore.setState({ lobby: lobbyData });

      // CURRENT: Mock implementation
      createLobby(roomName, maxPlayers);

      navigate('/lobby');
    } catch (err) {
      console.error('[CreateTeam] Error creating lobby:', err);
      setError(err.message);
      // TODO: BACKEND - Show error UI and allow retry
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="h-7/10 bg-gray-800 rounded-lg mr-10 ml-10 p-5 flex flex-col items-center text-3xl font-bold">
      Create a Team

      <div className="w-full max-w-md mt-8 text-white text-base font-normal">

        {/* Error Display (TODO: BACKEND) */}
        {error && (
          <div className="mb-6 p-3 bg-red-600 rounded">
            {error}
          </div>
        )}

        {/* Room Name */}
        <div className="mb-6">
          <label className="block mb-2 text-lg font-semibold">
            Room Name
          </label>
          <input
            type="text"
            value={roomName}
            onChange={(e) => setRoomName(e.target.value)}
            placeholder="Enter room name"
            disabled={isLoading}
            className="w-full p-3 rounded bg-gray-700 text-white outline-none focus:ring-2 focus:ring-blue-500 disabled:opacity-50"
          />
        </div>

        {/* Max Players */}
        <div className="mb-8">
          <label className="block mb-2 text-lg font-semibold">
            Max Players
          </label>
          <select
            value={maxPlayers}
            onChange={(e) => setMaxPlayers(Number(e.target.value))}
            disabled={isLoading}
            className="w-full p-3 rounded bg-gray-700 text-white outline-none disabled:opacity-50"
          >
            <option value={2}>2 Players</option>
            <option value={3}>3 Players</option>
            <option value={4}>4 Players</option>
          </select>
        </div>

        {/* Create Button */}
        <button
          onClick={handleCreate}
          disabled={isLoading || !roomName.trim()}
          className="w-full bg-blue-600 hover:bg-blue-500 text-white p-3 rounded font-bold transition disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isLoading ? 'Creating...' : 'Create Team'}
        </button>

      </div>
    </div>
  );
};

export default CreateTeam;